name: bayesian-demo
channels: [conda-forge]
dependencies:
  - python = 3.11
  - numpy = 1.26.*
  - matplotlib = 3.9.*
  - ipywidgets = 8.1.*      # widgets in the notebook
  - voila = 0.5.*           # optional: turns notebook into a web app
